# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2313b1e1539e0fd7a1df86a1094f802f5539986f0bc9a06f84b96718c87472cd9c7896589daf1c39255f574d60c7530b0f30137ea8dec4231a0a95817c244177

test:
  secret_key_base: e2809bec6b5b14521151c6f5f494ff712b4ed581c0d215ce2003ef1d747fc00d7d5ac684ef6ba49fc2e3007123e124ddde5ba6b14b280121afc7400d99700963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
